export const projects = [
  {
    title: 'Modern UI/UX Website GPT-3',
    description: "A Fully Responsive Modern UI/UX Website in React JS. I converted a Figma design into a fully functioning website, improved your CSS skills, and created a modern and responsive ReactJS website.",
      image: '/images/1.png',
      tags: ['React', 'JavaScript', 'CSS', 'HTML', 'Figma'],
      source: '',
      visit: 'https://gpt-3bysamridhi.netlify.app',
    id: 0,
  },
  {
    title: 'Alan AI News Application',
    description:"An Artificial Intelligence React News Application using Alan AI. Alan AI is a revolutionary speech recognition software that allows you to add voice capabilities to your applications. It allows you to control absolutely everything in the app using your voice.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: '',
    visit: 'https://alanainewsapplication.netlify.app',
    id: 1,
  },
  {
    title: 'Cryptoverse',
    description: "A React Cryptocurrency App which gives you all the information about cryptocurrencies.",
    image: '/images/3.png',
    tags: ['React', 'Redux', 'Ant Design', 'Chart.js', 'RapidAPI'],
    source: '',
    visit: 'https://cryptoversebysamridhi.netlify.app',
    id: 2,
  },
  {
    title: 'COVID-19 Tracker',
    description: "A COVID-19 Tracker Application. Corona Virus is, unfortunately, spreading through the entire world. What can we, as developers, do to make the situation better? We can help to spread awareness by visualizing the data.",
    image: '/images/4.png',
    tags: ['React', 'JavaScript', 'Material UI'],
    source: '',
    visit: 'https://coronatrackerbysamridhi.netlify.app',
    id: 3,
  },
  {
    title: 'E-commerce Store',
    description: "A fully functional E-commerce Web Shop.",
    image: '/images/5.png',
    tags: ['React', 'Commerce.js'],
    source: '',
    visit: 'https://e-commercebysamridhi.netlify.app',
    id: 4,
  },
  {
    title: 'Goggle- A Google 2.0',
    description: "A Google Search 2.0 with the ability to search for up-to-date results, images, news, and videos, modern UI, dark mode, this is a completely responsive Google Clone.",
    image: '/images/6.png',
    tags: ['React', 'Tailwind CSS'],
    source: '',
    visit: 'https://gogglebysamridhi.netlify.app',
    id: 5,
  },
  {
    title: 'Webchat Application',
    description: "This is kind of like a clone MS-Teams. You can create multiple rooms, send texts and photos, and much more.",
    image: '/images/7.png',
    tags: ['React', 'ChatEngine', 'Sockets'],
    source: '',
    visit: 'https://chatappsamridhi.netlify.app',
    id: 6,
  },
  {
    title: 'Weather PWA',
    description: "A Weather Progressive Web App.",
    image: '/images/8.png',
    tags: ['React', 'PWA', 'Lighthouse', 'Service Workers'],
    source: '',
    visit: 'https://weatherpwabysamridhi.netlify.app',
    id: 7,
  },
  {
    title: 'Travel Advisor',
    description: "A Google Maps Travel Companion Application. It is cureently undergoing a change.",
    image: '/images/9.png',
    tags: ['React', 'Geolocation', 'Google Maps API', 'Google Places API'],
    source: '',
    visit: 'https://traveladvisorbysamridhi.netlify.app',
    id: 8,
  },
  {
    title: 'Advice App',
    description: "An advice app which generates random quotes.",
    image: '/images/10.png',
    tags: ['React', 'API'],
    source: '',
    visit: 'https://adviceappbysamridhi.netlify.app',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'September- Started my journey as a programmer.', },
];